events {}

http {
    upstream gateway { server gateway:4000; }
    upstream portal  { server portal:3000;  }

    server {
        listen 80;

        location /v1/ {
            proxy_pass         http://gateway;
            proxy_set_header   Host $host;
            proxy_read_timeout 60s;
        }

        location /mgmt/ {
            proxy_pass         http://gateway;
            proxy_set_header   Host $host;
            proxy_read_timeout 60s;
        }

        location /health {
            proxy_pass http://gateway;
        }

        location / {
            proxy_pass         http://portal;
            proxy_set_header   Host $host;
            proxy_read_timeout 60s;
        }
    }
}
